#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1488944709                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1488944709   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ios-marketing.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Show Box & Movies Planner                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : You ever had the argument with your friends on what movie to watch.
                                            Our app will help you solve that problem.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Le Do                                
your_link                                 : http://movie360.github.io/
your_city                                 : HaNoi                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Map & Directions
    description                           : Find Movie Theaters Near You
    fontawesome_icon_name                 : location-arrow

  - title                                 : Make plan
    description                           : Creat plan with specific detail, and easy to share with friend
    fontawesome_icon_name                 : calendar-check

  - title                                 : Discover Popular Movies 
    description                           : Easy & All in one place
    fontawesome_icon_name                 : magic

  - title                                 : Using 3rd party TMDb service.
    description                           : The Movie Database (TMDb) is a community built movie and TV database. Every piece of data has been added by our amazing community dating back to 2008. 
    fontawesome_icon_name                 : link
  
  - title                                 : #Feature List
    description                           : #Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #star

  - title                                 : Contact
    description                           : 'Messenger: <a href="https://m.me/416305462459391">me</a><br>Email: <a href="mailto:appfeedback118@yandex.com">appfeedback118</a>'
    fontawesome_icon_name                 : address-card

  - title                                 : Privacy & Term of service
    description                           : <a href="https://movie360.github.io/docs/privacy">Privacy</a><br><a href="http://movie360.github.io/docs/term">Term of service</a>
    fontawesome_icon_name                 : user-shield



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
